name: release

on:
  release:
    types:
      - created

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set version
      run:
      with:
        go-version: 1.22

    - name: Check version
      run: go version

    - name: Build executables
      run: |
        export VERSION=${{ github.ref_name }}
        sed -i 's/Version = "dev"/Version = "'"$VERSION"'"/' internal/version.go

