name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Check if the Version changed
      id: version-changed
      run: |
        CURRENT_VERSION=$(grep -oP 'Version\s*=\s*"\K[^\"]+' ./internal/version.go)
        PREVIOUS_VERSION=$(git show ${{ github.event.before }}:internal/version.go | grep -oP 'Version\s*=\s*"\K[^\"]+')

        if [ "$CURRENT_VERSION" == "$PREVIOUS_VERSION" ]; then
          exit 1
        fi

    - name: Create a new release
      if: steps.version-changed.outcome == 'success'
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        CURRENT_VERSION=$(grep -oP 'Version\s*=\s*"\K[^\"]+' internal/version.go)

        gh release create $CURRENT_VERSION \
          --title "$CURRENT_VERSION" \
          --notes "New release version $CURRENT_VERSION"
