name: release

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check if the Version changed
      run:
        if [ "$(sed -n 's/.*Version = "\(.*\)"/\1/p' ./internal/version.go)" = "$(git show HEAD~1:./internal/version.go | sed -n 's/.*Version = "\(.*\)"/\1/p')" ]; then
          exit 0
        fi
    
    - name: Create tag
      run: |
        VERSION=$(sed -n 's/.*Version = "\(.*\)"/\1/p' ./internal/version.go)
        git tag -a "$VERSION" -m "Release version $VERSION"
        git push origin "$VERSION"

    - name: Create release
      uses: actions/create-release@v1
      with:
        tag_name: "v${{ steps.create_tag.outputs.VERSION }}"
        release_name: "Release ${{ steps.create_tag.outputs.VERSION }}"
        body: "Release version ${{ steps.create_tag.outputs.VERSION }}."
        draft: false
        prerelease: false
